name = "Real-Analysis-Self-Learning-"
version = "0.1.0"
defaultTargets = ["real-analysis-self-learning-"]

[[lean_lib]]
name = "RealAnalysisSelfLearning"

[[lean_exe]]
name = "real-analysis-self-learning-"
root = "Main"
